on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.issue.body;
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['wantsPR']
            })
            if(body.includes("- [X] I would like to do a Pull Request") {
              console.log("yes");
            } else {
              console.log("no");
            }
