on: pull_request

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body;
            let labels = [];
            const isChecked = /-\s*\[\s*[x|X]\s*\]\s*/;
            if(RegExp(isChecked.source + "Bug fix (non-breaking change which fixes an issue)")) {
              labels.push("bug");
              console.log("PR type: bug fix.");
            }
            
            if(RegExp(isChecked.source + "New feature (non-breaking change which adds functionality)")) {
              labels.push("enhancement");
              console.log("PR type: enhancement.");
            }

            if(RegExp(isChecked.source + "Breaking change (fix or feature that would cause existing functionality to not work as expected)")) {
              labels.push("breaking change");
              console.log("PR type: breaking change.");
            }
            
            if(!pr.draft) {
              labels.push("PR: needs review");
            }
            if(labels.length != 0) {
              github.rest.issues.addLabels({
                issue_number: 91,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              })
            }

            
